language: java

udo: false
install: true
addons:
  sonarcloud:
    organization: "mmalgorn-github"
    token:
      secure: "21e382b1e225561dc00582c9f4dfab62ca132006"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email:
    - m.malgorn29@gmail.com
    - gab151196@hotmail.fr

before_deploy:
   - mvn package

deploy:
  skip_cleanup: true
  file:
    - "target/dependency-jars/*"
  on:
    tags: false
    all_branches: true
