language: java
udo: false
install: true
addons:
  sonarcloud:
    organization: mmalgorn-github
    token:
      secure: 21e382b1e225561dc00582c9f4dfab62ca132006
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
  - m.malgorn29@gmail.com
  - gab151196@hotmail.fr

deploy:
  skip_cleanup: true
  provider: releases
  user: mmalgorn
  file:
  - /home/travis/build/mmalgorn/IGL601/target/Source-0.0.1-SNAPSHOT.jar
  on:
    tags: false
    all_branches: true
  api_key:
    secure: fj9aULIkIYNjzJuwEhw/EHyw1FBv5+/v4ACz/JHU+fToQEp1gECe2e/EbV06NwT2F3lW8BpByzaco8zIWkDEOMctVJTjg0XKz7e49Y9tG44jlL/z9q13sSVi/2dkNZRyPlUSb7YBoYqW/5q1EnXSIQXNxmhbUeGN1Rpuswq3qawqZ1cFwYG/pU3UxCXTT5cITzJwctz4UNAnwjsbqIatNKkWSJPVOTDPseo0Va0NZbb+YxkkiY1RWum2ZXP6ESawnmC6n0C2SbMIQ/4NoCV8Of102ak5wbVe81yn0mIvwKN72VWBETjMY3ow0R/sMPHe7LOYtjaKCbgF+9Du233FK7DFDAG/cU0GZ3TiEA1HQKZKNmo3UP6SudkHW52vlfcsllkZVY4Q6NCk/id+Yg1nzmI9MAmMTV7q53vAcVOSHvUzTJdzaxkKTHrUMBkzMpYGmWaaS1m5SZlCs46PwlJMdDb9Qh4dT4epteWcfpajeYdX1m5OvmNUJiJjtFZAK2UNcCyG4RYx3yJOf/JbcwSiOndvNlfZQm3TfhvGd98LhDMhDyWvFU9aE5aIPBgaShE6xe7QsgIyx6d5f/TOU1sKqwfrizKBAuT8au3lWtCBg/2tz6o4tKkbSo59ffQXdO/z9e60YMepdLQQcRiSY2+cExgHQySCFnWouSOw0O0j2l4=
